---
# config.yaml

# --- Input Data ---
# Path to the samplesheet CSV file.
# The CSV must have three columns: sample,fastq_1,fastq_2
samplesheet: "samples.csv"

# --- Reference Genome ---
# Make sure the reference is indexed (e.g., with `samtools faidx` and `bwa-mem2 index`).
ref_fasta: "giab_benchmark/data/reference/GRCh38/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz"
bwa_index: "giab_benchmark/data/reference/GRCh38/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz"

# --- Workflow Options ---
# Set to `true` to run the joint calling step with GLnexus.
joint_calling: true

# --- Container Images ---
# Specify the Docker or Singularity container images for each tool.
# Using specific versions ensures reproducibility.
containers:
  fastp: "docker://quay.io/biocontainers/fastp:0.23.2--h79da9fb_0"
  bwa_samtools: "docker://quay.io/biocontainers/bwa-mem2:2.2.1--h572174a_3" # This container also has samtools
  deepvariant: "docker://google/deepvariant:1.5.0"
  glnexus: "docker://quay.io/biocontainers/glnexus:1.4.1--h9ee0642_0"
  multiqc: "docker://quay.io/biocontainers/multiqc:1.14--pyhdfd78af_0"

# --- Optional Parameters ---
# Add extra command-line parameters for specific tools if needed.
# params:
#   fastp: "--detect_adapter_for_pe"

